version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev 
    volumes:
      - ./html:/html
    ports:
      - "3000:3000" # Port for BrowserSync server
      - "3001:3001" # Port for BrowserSync UI (optional)

